server {
  listen 80;
  server_name _;

  location /api/video/ {
    proxy_buffering off;
    proxy_pass http://video-runtime:8001;
  }

  location /chat-v1/ {
    proxy_buffering off;
    proxy_read_timeout 3600s;
    proxy_pass http://video-runtime:8001;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
