{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretEnvFrom }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  S3_BUCKET: ""
  S3_CDN_PREFIX: ""
{{- end }}
