apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cuti-cluster
  region: ap-southeast-2

vpc:
  id: "vpc-0cc2ca6f9f8545227"
  subnets:
    public:
      ap-southeast-2a: { id: "subnet-0bf453fe72ddec405" }
      ap-southeast-2b: { id: "subnet-0ffcdae24cf683e02" }
      ap-southeast-2c: { id: "subnet-0f3c38b136b0568d2" }

managedNodeGroups:
  - name: media-workers
    instanceType: c6i.xlarge
    desiredCapacity: 2
    minSize: 2
    maxSize: 12
    volumeSize: 50
    volumeType: gp3
    labels:
      workload: media-processing
    tags:
      Project: cuti-media-service
    iam:
      withAddonPolicies:
        albIngress: true
        cloudWatch: true

iam:
  withOIDC: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
